language: ruby
before_script:
  - sudo apt-get install git -y

rvm:
  - 1.9.3
  
script: 
  - git 

after_script:
  - cp id_rsa ~/.ssh/id_rsa
  - ssh maodou@182.92.71.18
  - scp id_rsa maodou@182.92.71.18:~
  - touch "I-am-a-good-boy"
  
